apiVersion: apps/v1
kind: Deployment
metadata:
  name: finaldeploy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: finalpod
  template:
    metadata:
      labels:
        app: finalpod
    spec:
      containers:
      - name: finalcontainer
        image: abhishek00007/finalproject:v.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: final-service
spec:
  selector:
    app: finalpod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31005
  type: NodePort  
